#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

GPUS="${GPUS:-1,2,3}"
SUITE_ROOT="${SUITE_ROOT:-runs/paper_suite_smoke}"

HPO_SEEDS="${HPO_SEEDS:-1}"
FINAL_SEEDS="${FINAL_SEEDS:-2}"
HPO_TRIALS="${HPO_TRIALS:-2}"
HPO_STEPS="${HPO_STEPS:-5}"
FINAL_STEPS="${FINAL_STEPS:-5}"
EVAL_EVERY="${EVAL_EVERY:-5}"
LOCAL_TOPK="${LOCAL_TOPK:-1}"
LOCAL_GRID_POINTS="${LOCAL_GRID_POINTS:-1}"
SKIP_MVP="${SKIP_MVP:-1}"

echo "[smoke] suite_root=$SUITE_ROOT gpus=$GPUS"
echo "[smoke] hpo_trials=$HPO_TRIALS hpo_seeds=$HPO_SEEDS final_seeds=$FINAL_SEEDS steps=$HPO_STEPS/$FINAL_STEPS"

GPUS="$GPUS" \
SUITE_ROOT="$SUITE_ROOT" \
HPO_SEEDS="$HPO_SEEDS" \
FINAL_SEEDS="$FINAL_SEEDS" \
HPO_TRIALS="$HPO_TRIALS" \
HPO_STEPS="$HPO_STEPS" \
FINAL_STEPS="$FINAL_STEPS" \
EVAL_EVERY="$EVAL_EVERY" \
LOCAL_TOPK="$LOCAL_TOPK" \
LOCAL_GRID_POINTS="$LOCAL_GRID_POINTS" \
SKIP_MVP="$SKIP_MVP" \
BACKBONES="deberta" \
TASKS="mrpc" \
bash scripts/run_single_task_suite_gpu01.sh

GPUS="$GPUS" \
SUITE_ROOT="$SUITE_ROOT" \
HPO_SEEDS="$HPO_SEEDS" \
FINAL_SEEDS="$FINAL_SEEDS" \
HPO_TRIALS="$HPO_TRIALS" \
HPO_STEPS="$HPO_STEPS" \
FINAL_STEPS="$FINAL_STEPS" \
EVAL_EVERY="$EVAL_EVERY" \
LOCAL_TOPK="$LOCAL_TOPK" \
LOCAL_GRID_POINTS="$LOCAL_GRID_POINTS" \
SKIP_MVP="$SKIP_MVP" \
BACKBONES="deberta,gpt2" \
MIXES="glue3" \
HF_NAME_GPT2="${HF_NAME_GPT2:-gpt2-medium}" \
bash scripts/run_multi_task_suite_gpu01.sh

GPUS="$GPUS" \
SUITE_ROOT="$SUITE_ROOT" \
HPO_SEEDS="$HPO_SEEDS" \
FINAL_SEEDS="$FINAL_SEEDS" \
HPO_TRIALS="$HPO_TRIALS" \
HPO_STEPS="$HPO_STEPS" \
FINAL_STEPS="$FINAL_STEPS" \
EVAL_EVERY="$EVAL_EVERY" \
LOCAL_TOPK="$LOCAL_TOPK" \
LOCAL_GRID_POINTS="$LOCAL_GRID_POINTS" \
SKIP_MVP="$SKIP_MVP" \
BACKBONE="deberta" \
bash scripts/run_minimal_ablation_suite_gpu01.sh

GPUS="$GPUS" \
SUITE_ROOT="$SUITE_ROOT" \
HPO_SEEDS="$HPO_SEEDS" \
FINAL_SEEDS="$FINAL_SEEDS" \
HPO_TRIALS="$HPO_TRIALS" \
HPO_STEPS="$HPO_STEPS" \
FINAL_STEPS="$FINAL_STEPS" \
EVAL_EVERY="$EVAL_EVERY" \
LOCAL_TOPK="$LOCAL_TOPK" \
LOCAL_GRID_POINTS="$LOCAL_GRID_POINTS" \
SKIP_MVP="$SKIP_MVP" \
BACKBONE="deberta" \
RANKS="16" \
TEXTCLS_TRAIN_SIZE="${TEXTCLS_TRAIN_SIZE:-64}" \
TEXTCLS_VAL_SIZE="${TEXTCLS_VAL_SIZE:-32}" \
bash scripts/run_appendix_experiment_suite_gpu01.sh

echo "done: $SUITE_ROOT"
